import pygame as pg

from gbemu.ctypes import Color

DEFAULT_ROM = "./roms/tetris.gb"

DEBUG = False
HEADLESS = False

# screen/ppu config
DISPLAY_SCALER: int = 3
SCREEN_WIDTH: int = 160
SCREEN_HEIGHT: int = 144
SCREEN_AREA: int = SCREEN_WIDTH * SCREEN_HEIGHT

BG_COLOR: Color = (202, 220, 159)
PALLETE: list[Color] = [
    (155, 188, 15),
    (139, 172, 15),
    (48, 98, 48),
    (15, 56, 15),
]
TILE_WIDTH: int = 8
TILE_BITS: int = 16

SHOW_FPS_OVERLAY: bool = True
FPS_BG_COLOR: Color = (0, 0, 0)
FPS_COLOR: Color = (255, 255, 255)


# Keyboard mapping to joypad bit mask and line-select (dpad=True, buttons=False)
KEYMAP: dict[int, tuple[int, bool]] = {
    pg.K_UP: (0b0100, True),
    pg.K_w: (0b0100, True),
    pg.K_DOWN: (0b1000, True),
    pg.K_s: (0b1000, True),
    pg.K_LEFT: (0b0010, True),
    pg.K_RIGHT: (0b0001, True),
    pg.K_d: (0b0001, True),
    pg.K_a: (0b0001, False),
    pg.K_j: (0b0001, False),
    pg.K_b: (0b0010, False),
    pg.K_k: (0b0010, False),
    pg.K_RETURN: (0b1000, False),
    pg.K_LSHIFT: (0b0100, False),
    pg.K_RSHIFT: (0b0100, False),
}

# Cartridge metadata mappings
CART_TYPE: dict[int, str] = {
    0x00: "ROM ONLY",
    0x01: "MBC1",
    0x02: "MBC1+RAM",
    0x03: "MBC1+RAM+BATTERY",
    0x05: "MBC2",
    0x06: "MBC2+BATTERY",
    0x08: "ROM+RAM",
    0x09: "ROM+RAM+BATTERY",
    0x0B: "MMM01",
    0x0C: "MMM01+RAM",
    0x0D: "MMM01+RAM+BATTERY",
    0x0F: "MBC3+TIMER+BATTERY",
    0x10: "MBC3+TIMER+RAM+BATTERY",
    0x11: "MBC3",
    0x12: "MBC3+RAM",
    0x13: "MBC3+RAM+BATTERY",
    0x19: "MBC5",
    0x1A: "MBC5+RAM",
    0x1B: "MBC5+RAM+BATTERY",
    0x1C: "MBC5+RUMBLE",
    0x1D: "MBC5+RUMBLE+RAM",
    0x1E: "MBC5+RUMBLE+RAM+BATTERY",
    0x20: "MBC6",
    0x22: "MBC7+SENSOR+RUMBLE+RAM+BATTERY",
    0xFC: "POCKET CAMERA",
    0xFD: "BANDAI TAMA5",
    0xFE: "HuC3",
    0xFF: "HuC1+RAM+BATTERY",
}

CGB_FLAG: dict[str, str] = {
    "00": "GB",
    "80": "CGB",
    "C0": "CGB+DMG",
}

MMU_SIZE: dict[int, str] = {
    0x00: "None",
    0x01: "Unused",
    0x02: "8 KB",
    0x03: "32 KB",
    0x04: "128 KB",
    0x05: "64 KB",
}

DESTINATION_CODE: dict[int, str] = {
    0x00: "Japan & Overseas",
    0x01: "Non-Japan",
}

NEW_LICENSEE: dict[str, str] = {
    "0": "None",
    "1": "Nintendo Research & Development 1",
    "8": "Capcom",
    "13": "EA (Electronic Arts)",
    "18": "Hudson Soft",
    "19": "B-AI",
    "20": "KSS",
    "22": "Planning Office WADA",
    "24": "PCM Complete",
    "25": "San-X",
    "28": "Kemco",
    "29": "SETA Corporation",
    "30": "Viacom",
    "31": "Nintendo",
    "32": "Bandai",
    "33": "Ocean Software/Acclaim Entertainment",
    "34": "Konami",
    "35": "HectorSoft",
    "37": "Taito",
    "38": "Hudson Soft",
    "39": "Banpresto",
    "41": "Ubi Soft",
    "42": "Atlus",
    "44": "Malibu Interactive",
    "46": "Angel",
    "47": "Bullet-Proof Software",
    "49": "Irem",
    "50": "Absolute",
    "51": "Acclaim Entertainment",
    "52": "Activision",
    "53": "Sammy USA Corporation",
    "54": "Konami",
    "55": "Hi Tech Expressions",
    "56": "LJN",
    "57": "Matchbox",
    "58": "Mattel",
    "59": "Milton Bradley Company",
    "60": "Titus Interactive",
    "61": "Virgin Games Ltd.",
    "64": "Lucasfilm Games",
    "67": "Ocean Software",
    "69": "EA (Electronic Arts)",
    "70": "Infogrames",
    "71": "Interplay Entertainment",
    "72": "Broderbund",
    "73": "Sculptured Software",
    "75": "The Sales Curve Limited",
    "78": "THQ",
    "79": "Accolade",
    "80": "Misawa Entertainment",
    "83": "lozc",
    "86": "Tokuma Shoten",
    "87": "Tsukuda Original",
    "91": "Chunsoft Co.",
    "92": "Video System",
    "93": "Ocean Software/Acclaim Entertainment",
    "95": "Varie",
    "96": "Yonezawa",
    "97": "Kaneko",
    "99": "Pack-In-Video",
    "9H": "Bottom Up",
    "A4": "Konami (Yu-Gi-Oh!)",
    "BL": "MTO",
    "DK": "Kodansha",
}

OLD_LICENSEE: dict[str, str] = {
    "0": "None",
    "1": "Nintendo",
    "8": "Capcom",
    "9": "HOT-B",
    "A": "Jaleco",
    "B": "Coconuts Japan",
    "C": "Elite Systems",
    "13": "EA (Electronic Arts)",
    "18": "Hudson Soft",
    "19": "ITC Entertainment",
    "1A": "Yanoman",
    "1D": "Japan Clary",
    "1F": "Virgin Games Ltd.",
    "24": "PCM Complete",
    "25": "San-X",
    "28": "Kemco",
    "29": "SETA Corporation",
    "30": "Infogrames",
    "31": "Nintendo",
    "32": "Bandai",
    "33": "NEW_LICENSEE",
    "34": "Konami",
    "35": "HectorSoft",
    "38": "Capcom",
    "39": "Banpresto",
    "3C": "Entertainment Interactive (stub)",
    "3E": "Gremlin",
    "41": "Ubi Soft",
    "42": "Atlus",
    "44": "Malibu Interactive",
    "46": "Angel",
    "47": "Spectrum HoloByte",
    "49": "Irem",
    "4A": "Virgin Games Ltd.",
    "4D": "Malibu Interactive",
    "4F": "U.S. Gold",
    "50": "Absolute",
    "51": "Acclaim Entertainment",
    "52": "Activision",
    "53": "Sammy USA Corporation",
    "54": "GameTek",
    "55": "Park Place",
    "56": "LJN",
    "57": "Matchbox",
    "59": "Milton Bradley Company",
    "5A": "Mindscape",
    "5B": "Romstar",
    "5C": "Naxat Soft",
    "5D": "Tradewest",
    "60": "Titus Interactive",
    "61": "Virgin Games Ltd.",
    "67": "Ocean Software",
    "69": "EA (Electronic Arts)",
    "6E": "Elite Systems",
    "6F": "Electro Brain",
    "70": "Infogrames",
    "71": "Interplay Entertainment",
    "72": "Broderbund",
    "73": "Sculptured Software",
    "75": "The Sales Curve Limited",
    "78": "THQ",
    "79": "Accolade",
    "7A": "Triffix Entertainment",
    "7C": "MicroProse",
    "7F": "Kemco",
    "80": "Misawa Entertainment",
    "83": "LOZC G.",
    "86": "Tokuma Shoten",
    "8B": "Bullet-Proof Software",
    "8C": "Vic Tokai Corp.",
    "8E": "Ape Inc.",
    "8F": "I'Max",
    "91": "Chunsoft Co.",
    "92": "Video System",
    "93": "Tsubaraya Productions",
    "95": "Varie",
    "96": "Yonezawa/S'Pal",
    "97": "Kemco",
    "99": "Arc",
    "9A": "Nihon Bussan",
    "9B": "Tecmo",
    "9C": "Imagineer",
    "9D": "Banpresto",
    "9F": "Nova",
    "A1": "Hori Electric",
    "A2": "Bandai",
    "A4": "Konami",
    "A6": "Kawada",
    "A7": "Takara",
    "A9": "Technos Japan",
    "AA": "Broderbund",
    "AC": "Toei Animation",
    "AD": "Toho",
    "AF": "Namco",
    "B0": "Acclaim Entertainment",
    "B1": "ASCII Corporation or Nexsoft",
    "B2": "Bandai",
    "B4": "Square Enix",
    "B6": "HAL Laboratory",
    "B7": "SNK",
    "B9": "Pony Canyon",
    "BA": "Culture Brain",
    "BB": "Sunsoft",
    "BD": "Sony Imagesoft",
    "BF": "Sammy Corporation",
    "C0": "Taito",
    "C2": "Kemco",
    "C3": "Square",
    "C4": "Tokuma Shoten",
    "C5": "Data East",
    "C6": "Tonkin House",
    "C8": "Koei",
    "C9": "UFL",
    "CA": "Ultra Games",
    "CB": "VAP, Inc.",
    "CC": "Use Corporation",
    "CD": "Meldac",
    "CE": "Pony Canyon",
    "CF": "Angel",
    "D0": "Taito",
    "D1": "SOFEL (Software Engineering Lab)",
    "D2": "Quest",
    "D3": "Sigma Enterprises",
    "D4": "ASK Kodansha Co.",
    "D6": "Naxat Soft",
    "D7": "Copya System",
    "D9": "Banpresto",
    "DA": "Tomy",
    "DB": "LJN",
    "DD": "Nippon Computer Systems",
    "DE": "Human Ent.",
    "DF": "Altron",
    "E0": "Jaleco",
    "E1": "Towa Chiki",
    "E2": "Yutaka",
    "E3": "Varie",
    "E5": "Epoch",
    "E7": "Athena",
    "E8": "Asmik Ace Entertainment",
    "E9": "Natsume",
    "EA": "King Records",
    "EB": "Atlus",
    "EC": "Epic/Sony Records",
    "EE": "IGS",
    "F0": "A Wave",
    "F3": "Extreme Entertainment",
    "FF": "LJN",
}
