from dataclasses import dataclass


@dataclass(frozen=True)
class OpCode:
    """GB CPU instruction."""

    label: str  # mnemonic name
    length: int  # length of instruction in bytes
    cycles: int  # number of cpu cyles
    call: str  # CPU method name to call
    args: list[str | bool] | None = None  # give arguments to send to CPU method
    flags: dict[str, int] | None = None  # set CPU flags after execution

    def __str__(self) -> str:
        return f"{self.label} {self.length} - {self.args} - {self.flags}"


OPCODES: dict[str, OpCode] = {
    "0x0": OpCode("NOP", 1, 4, "nop"),
    "0x1": OpCode("LD BC, d16", 3, 12, "ld", args=["BC"]),
    "0x2": OpCode("LD [BC], A", 1, 8, "ld_mem", args=["BC", "A"]),
    "0x3": OpCode("INC BC", 1, 8, "inc", args=["BC"]),
    "0x4": OpCode("INC B", 1, 8, "inc", args=["B"], flags={"N": 0}),
    "0x5": OpCode("DEC B", 1, 8, "dec", args=["B"], flags={"N": 1}),
    "0x6": OpCode("LD B, d8", 2, 8, "ld", args=["B"]),
    "0x7": OpCode(
        "RLCA",
        1,
        4,
        "rotate",
        args=["A", True, True],
        flags={"Z": 0, "N": 0, "H": 0},
    ),
    "0x8": OpCode("LD [a16], SP", 3, 20, "ld_mem_sp"),
    "0x9": OpCode("ADD HL, BC", 1, 8, "add16", args=["HL", "BC"], flags={"N": 0}),
    "0xf": OpCode(
        "RRCA",
        1,
        4,
        "rotate",
        args=["A", False, True],
        flags={"Z": 0, "N": 0, "H": 0},
    ),
    "0x10": OpCode("STOP", 2, 4, "stop"),  # NEEDS TESTING
    "0x11": OpCode("LD DE, d16", 3, 12, "ld", args=["DE"]),
    "0x12": OpCode("LD [DE], A", 1, 8, "ld_mem", args=["DE", "A"]),
    "0x13": OpCode("INC DE", 1, 8, "inc", args=["DE"]),
    "0x14": OpCode("INC D", 1, 8, "inc", args=["D"], flags={"N": 0}),
    "0x15": OpCode("DEC D", 1, 8, "dec", args=["D"], flags={"N": 1}),
    "0x16": OpCode("LD D, d8", 2, 8, "ld", args=["D"]),
    "0x17": OpCode(
        "RLA",
        1,
        4,
        "rotate",
        args=["A", True, False, True],
        flags={"Z": 0, "N": 0, "H": 0},
    ),
    "0x19": OpCode("ADD HL, DE", 1, 8, "add16", args=["HL", "DE"], flags={"N": 0}),
    "0x1f": OpCode(
        "RRA",
        1,
        4,
        "rotate",
        args=["A", False, False, True],
        flags={"Z": 0, "N": 0, "H": 0},
    ),
    "0x21": OpCode("LD HL, d16", 3, 12, "ld", args=["HL"]),
    "0x23": OpCode("INC HL", 1, 8, "inc", args=["HL"]),
    "0x24": OpCode("INC H", 1, 8, "inc", args=["H"], flags={"N": 0}),
    "0x25": OpCode("DEC H", 1, 8, "dec", args=["H"], flags={"N": 1}),
    "0x26": OpCode("LD H, d8", 2, 8, "ld", args=["H"]),
    "0x29": OpCode("ADD HL, HL", 1, 8, "add16", args=["HL", "HL"], flags={"N": 0}),
    "0x31": OpCode("LD SP, d16", 3, 12, "ld", args=["SP"]),
    "0x33": OpCode("INC SP", 1, 8, "inc", args=["SP"]),
    "0x34": OpCode("INC [HL]", 1, 12, "inc_mem", args=["HL"], flags={"N": 0}),
    "0x35": OpCode("DEC [HL]", 1, 12, "dec_mem", args=["HL"], flags={"N": 1}),
    "0x36": OpCode("LD [HL], d8", 2, 12, "ld_mem", args=["HL"]),
    "0x39": OpCode("ADD HL, SP", 1, 8, "add16", args=["HL", "SP"], flags={"N": 0}),
    "0x3e": OpCode("LD A, d8", 2, 8, "ld", args=["A"]),
    "0x40": OpCode("LD B, B", 1, 4, "ld", args=["B", "B"]),
    "0x41": OpCode("LD B, C", 1, 4, "ld", args=["B", "C"]),
    "0x42": OpCode("LD B, D", 1, 4, "ld", args=["B", "D"]),
    "0x43": OpCode("LD B, E", 1, 4, "ld", args=["B", "E"]),
    "0x44": OpCode("LD B, H", 1, 4, "ld", args=["B", "H"]),
    "0x45": OpCode("LD B, L", 1, 4, "ld", args=["B", "L"]),
    "0x46": OpCode("LD B, [HL]", 1, 8, "ld_hl", args=["B"]),
    "0x47": OpCode("LD B, A", 1, 4, "ld", args=["B", "A"]),
    "0x48": OpCode("LD C, B", 1, 4, "ld", args=["C", "B"]),
    "0x49": OpCode("LD C, C", 1, 4, "ld", args=["C", "C"]),
    "0x4a": OpCode("LD C, D", 1, 4, "ld", args=["C", "D"]),
    "0x4b": OpCode("LD C, E", 1, 4, "ld", args=["C", "E"]),
    "0x4c": OpCode("LD C, H", 1, 4, "ld", args=["C", "H"]),
    "0x4d": OpCode("LD C, L", 1, 4, "ld", args=["C", "L"]),
    "0x4e": OpCode("LD C, [HL]", 1, 8, "ld_hl", args=["C"]),
    "0x4f": OpCode("LD C, A", 1, 4, "ld", args=["C", "A"]),
    "0x50": OpCode("LD D, B", 1, 4, "ld", args=["D", "B"]),
    "0x51": OpCode("LD D, C", 1, 4, "ld", args=["D", "C"]),
    "0x52": OpCode("LD D, D", 1, 4, "ld", args=["D", "D"]),
    "0x53": OpCode("LD D, E", 1, 4, "ld", args=["D", "E"]),
    "0x54": OpCode("LD D, H", 1, 4, "ld", args=["D", "H"]),
    "0x55": OpCode("LD D, L", 1, 4, "ld", args=["D", "L"]),
    "0x56": OpCode("LD D, [HL]", 1, 8, "ld_hl", args=["D"]),
    "0x57": OpCode("LD D, A", 1, 4, "ld", args=["D", "A"]),
    "0x58": OpCode("LD E, B", 1, 4, "ld", args=["E", "B"]),
    "0x59": OpCode("LD E, C", 1, 4, "ld", args=["E", "C"]),
    "0x5a": OpCode("LD E, D", 1, 4, "ld", args=["E", "D"]),
    "0x5b": OpCode("LD E, E", 1, 4, "ld", args=["E", "E"]),
    "0x5c": OpCode("LD E, H", 1, 4, "ld", args=["E", "H"]),
    "0x5d": OpCode("LD E, L", 1, 4, "ld", args=["E", "L"]),
    "0x5e": OpCode("LD E, [HL]", 1, 8, "ld_hl", args=["E"]),
    "0x5f": OpCode("LD E, A", 1, 4, "ld", args=["E", "A"]),
    "0x60": OpCode("LD H, B", 1, 4, "ld", args=["H", "B"]),
    "0x61": OpCode("LD H, C", 1, 4, "ld", args=["H", "C"]),
    "0x62": OpCode("LD H, D", 1, 4, "ld", args=["H", "D"]),
    "0x63": OpCode("LD H, E", 1, 4, "ld", args=["H", "E"]),
    "0x64": OpCode("LD H, H", 1, 4, "ld", args=["H", "H"]),
    "0x65": OpCode("LD H, L", 1, 4, "ld", args=["H", "L"]),
    "0x66": OpCode("LD H, [HL]", 1, 8, "ld_hl", args=["H"]),
    "0x67": OpCode("LD H, A", 1, 4, "ld", args=["H", "A"]),
    "0x68": OpCode("LD L, B", 1, 4, "ld", args=["L", "B"]),
    "0x69": OpCode("LD L, C", 1, 4, "ld", args=["L", "C"]),
    "0x6a": OpCode("LD L, D", 1, 4, "ld", args=["L", "D"]),
    "0x6b": OpCode("LD L, E", 1, 4, "ld", args=["L", "E"]),
    "0x6c": OpCode("LD L, H", 1, 4, "ld", args=["L", "H"]),
    "0x6d": OpCode("LD L, L", 1, 4, "ld", args=["L", "L"]),
    "0x6e": OpCode("LD L, [HL]", 1, 8, "ld_hl", args=["L"]),
    "0x6f": OpCode("LD L, A", 1, 4, "ld", args=["L", "A"]),
    "0x70": OpCode("LD [HL], B", 1, 8, "ld_mem", args=["HL", "B"]),
    "0x71": OpCode("LD [HL], C", 1, 8, "ld_mem", args=["HL", "C"]),
    "0x72": OpCode("LD [HL], D", 1, 8, "ld_mem", args=["HL", "D"]),
    "0x73": OpCode("LD [HL], E", 1, 8, "ld_mem", args=["HL", "E"]),
    "0x74": OpCode("LD [HL], H", 1, 8, "ld_mem", args=["HL", "H"]),
    "0x75": OpCode("LD [HL], L", 1, 8, "ld_mem", args=["HL", "L"]),
    "0x76": OpCode("HALT", 1, 4, "halt"),  # NEEDS INTERRUPT HANDLING / TESTING
    "0x77": OpCode("LD [HL], A", 1, 8, "ld_mem", args=["HL", "A"]),
    "0x78": OpCode("LD A, B", 1, 4, "ld", args=["A", "B"]),
    "0x79": OpCode("LD A, C", 1, 4, "ld", args=["A", "C"]),
    "0x7a": OpCode("LD A, D", 1, 4, "ld", args=["A", "D"]),
    "0x7b": OpCode("LD A, E", 1, 4, "ld", args=["A", "E"]),
    "0x7c": OpCode("LD A, H", 1, 4, "ld", args=["A", "H"]),
    "0x7d": OpCode("LD A, L", 1, 4, "ld", args=["A", "L"]),
    "0x7e": OpCode("LD A, [HL]", 1, 8, "ld_hl", args=["A"]),
    "0x7f": OpCode("LD A, A", 1, 4, "ld", args=["A", "A"]),
    "0x80": OpCode("ADD A, B", 1, 4, "add", args=["A", "B"], flags={"N": 0}),
    "0x81": OpCode("ADD A, C", 1, 4, "add", args=["A", "C"], flags={"N": 0}),
    "0x82": OpCode("ADD A, D", 1, 4, "add", args=["A", "D"], flags={"N": 0}),
    "0x83": OpCode("ADD A, E", 1, 4, "add", args=["A", "E"], flags={"N": 0}),
    "0x84": OpCode("ADD A, H", 1, 4, "add", args=["A", "H"], flags={"N": 0}),
    "0x85": OpCode("ADD A, L", 1, 4, "add", args=["A", "L"], flags={"N": 0}),
    "0x86": OpCode("ADD A, [HL]", 1, 8, "add", args=["A", "HL"], flags={"N": 0}),
    "0x87": OpCode("ADD A, A", 1, 4, "add", args=["A", "A"], flags={"N": 0}),
    "0x88": OpCode("ADC A, B", 1, 4, "add", args=["A", "B", True], flags={"N": 0}),
    "0x89": OpCode("ADC A, C", 1, 4, "add", args=["A", "C", True], flags={"N": 0}),
    "0x8a": OpCode("ADC A, D", 1, 4, "add", args=["A", "D", True], flags={"N": 0}),
    "0x8b": OpCode("ADC A, E", 1, 4, "add", args=["A", "E", True], flags={"N": 0}),
    "0x8c": OpCode("ADC A, H", 1, 4, "add", args=["A", "H", True], flags={"N": 0}),
    "0x8d": OpCode("ADC A, L", 1, 4, "add", args=["A", "L", True], flags={"N": 0}),
    "0x8e": OpCode("ADC A, [HL]", 1, 8, "add", args=["A", "HL", True], flags={"N": 0}),
    "0x8f": OpCode("ADC A, A", 1, 4, "add", args=["A", "A", True], flags={"N": 0}),
    "0x90": OpCode("SUB A, B", 1, 4, "sub", args=["A", "B"], flags={"N": 1}),
    "0x91": OpCode("SUB A, C", 1, 4, "sub", args=["A", "C"], flags={"N": 1}),
    "0x92": OpCode("SUB A, D", 1, 4, "sub", args=["A", "D"], flags={"N": 1}),
    "0x93": OpCode("SUB A, E", 1, 4, "sub", args=["A", "E"], flags={"N": 1}),
    "0x94": OpCode("SUB A, [HL]", 1, 8, "sub", args=["A", "HL"], flags={"N": 1}),
    "0x95": OpCode("SUB A, A", 1, 4, "sub", args=["A", "A"], flags={"N": 1}),
    "0x96": OpCode("SBC A, B", 1, 4, "sub", args=["A", "B", True], flags={"N": 1}),
    "0x97": OpCode("SBC A, C", 1, 4, "sub", args=["A", "C", True], flags={"N": 1}),
    "0x98": OpCode("SBC A, D", 1, 4, "sub", args=["A", "D", True], flags={"N": 1}),
    "0x99": OpCode("SBC A, E", 1, 4, "sub", args=["A", "E", True], flags={"N": 1}),
    "0x9a": OpCode("SBC A, H", 1, 4, "sub", args=["A", "H", True], flags={"N": 1}),
    "0x9b": OpCode("SBC A, L", 1, 4, "sub", args=["A", "L", True], flags={"N": 1}),
    "0x9c": OpCode("SBC A, [HL]", 1, 8, "sub", args=["A", "HL", True], flags={"N": 1}),
    "0x9d": OpCode("SBC A, A", 1, 4, "sub", args=["A", "A", True], flags={"N": 1}),
    "0xa0": OpCode(
        "AND A, B",
        1,
        4,
        "bitwise",
        args=["AND", "A", "B"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa1": OpCode(
        "AND A, C",
        1,
        4,
        "bitwise",
        args=["AND", "A", "C"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa2": OpCode(
        "AND A, D",
        1,
        4,
        "bitwise",
        args=["AND", "A", "D"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa3": OpCode(
        "AND A, E",
        1,
        4,
        "bitwise",
        args=["AND", "A", "E"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa4": OpCode(
        "AND A, H",
        1,
        4,
        "bitwise",
        args=["AND", "A", "H"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa5": OpCode(
        "AND A, L",
        1,
        4,
        "bitwise",
        args=["AND", "A", "L"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa6": OpCode(
        "AND A, [HL]",
        1,
        8,
        "bitwise",
        args=["AND", "A", "HL"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa7": OpCode(
        "AND A, A",
        1,
        4,
        "bitwise",
        args=["AND", "A", "A"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa8": OpCode(
        "XOR A, B",
        1,
        4,
        "bitwise",
        args=["XOR", "A", "B"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xa9": OpCode(
        "XOR A, C",
        1,
        4,
        "bitwise",
        args=["XOR", "A", "C"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xaa": OpCode(
        "XOR A, D",
        1,
        4,
        "bitwise",
        args=["XOR", "A", "D"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xab": OpCode(
        "XOR A, E",
        1,
        4,
        "bitwise",
        args=["XOR", "A", "E"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xac": OpCode(
        "XOR A, H",
        1,
        4,
        "bitwise",
        args=["XOR", "A", "H"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xad": OpCode(
        "XOR A, L",
        1,
        4,
        "bitwise",
        args=["XOR", "A", "L"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xae": OpCode(
        "XOR A, [HL]",
        1,
        8,
        "bitwise",
        args=["XOR", "A", "HL"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xaf": OpCode(
        "XOR A, A",
        1,
        4,
        "bitwise",
        args=["XOR", "A", "A"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb0": OpCode(
        "OR A, B",
        1,
        4,
        "bitwise",
        args=["OR", "A", "B"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb1": OpCode(
        "OR A, C",
        1,
        4,
        "bitwise",
        args=["OR", "A", "C"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb2": OpCode(
        "OR A, D",
        1,
        4,
        "bitwise",
        args=["OR", "A", "D"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb3": OpCode(
        "OR A, E",
        1,
        4,
        "bitwise",
        args=["OR", "A", "E"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb4": OpCode(
        "OR A, H",
        1,
        4,
        "bitwise",
        args=["OR", "A", "H"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb5": OpCode(
        "OR A, L",
        1,
        4,
        "bitwise",
        args=["OR", "A", "L"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb6": OpCode(
        "OR A, [HL]",
        1,
        8,
        "bitwise",
        args=["OR", "A", "HL"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb7": OpCode(
        "OR A, A",
        1,
        4,
        "bitwise",
        args=["OR", "A", "A"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb8": OpCode(
        "CP A, B",
        1,
        4,
        "cp",
        args=["A", "B"],
        flags={"N": 1},
    ),
    "0xb9": OpCode(
        "CP A, C",
        1,
        4,
        "cp",
        args=["A", "C"],
        flags={"N": 1},
    ),
    "0xba": OpCode(
        "CP A, D",
        1,
        4,
        "cp",
        args=["A", "D"],
        flags={"N": 1},
    ),
    "0xbb": OpCode(
        "CP A, E",
        1,
        4,
        "cp",
        args=["A", "E"],
        flags={"N": 1},
    ),
    "0xbc": OpCode(
        "CP A, H",
        1,
        4,
        "cp",
        args=["A", "H"],
        flags={"N": 1},
    ),
    "0xbd": OpCode(
        "CP A, L",
        1,
        4,
        "cp",
        args=["A", "L"],
        flags={"N": 1},
    ),
    "0xbe": OpCode(
        "CP A, [HL]",
        1,
        8,
        "cp",
        args=["A", "HL"],
        flags={"N": 1},
    ),
    "0xbf": OpCode(
        "CP A, A",
        1,
        4,
        "cp",
        args=["A", "A"],
        flags={"N": 1, "Z": 1, "H": 0, "C": 0},
    ),
}
