from gbemu.ctypes import Bitwise, OpCode

OPCODES: dict[str, OpCode] = {
    "0x0": OpCode("NOP", 1, 4, "nop"),
    "0x1": OpCode("LD BC, d16", 3, 12, "ld", args=["BC"]),
    "0x2": OpCode("LD [BC], A", 1, 8, "ld_mem", args=["BC", "A"]),
    "0x3": OpCode("INC BC", 1, 8, "inc", args=["BC"]),
    "0x4": OpCode("INC B", 1, 8, "inc", args=["B"], flags={"N": 0}),
    "0x5": OpCode("DEC B", 1, 8, "dec", args=["B"], flags={"N": 1}),
    "0x6": OpCode("LD B, d8", 2, 8, "ld", args=["B"]),
    "0x7": OpCode(
        "RLCA",
        1,
        4,
        "rot",
        args=["A", True, True],
        flags={"Z": 0, "N": 0, "H": 0},
    ),
    "0x8": OpCode("LD [a16], SP", 3, 20, "ld_mem_sp"),
    "0x9": OpCode("ADD HL, BC", 1, 8, "add16", args=["HL", "BC"], flags={"N": 0}),
    "0xa": OpCode("LD A, [BC]", 1, 8, "ld_reg16", args=["A", "BC"]),
    "0xb": OpCode("DEC BC", 1, 8, "dec", args=["BC"]),
    "0xc": OpCode("INC C", 1, 8, "inc", args=["C"], flags={"N": 0}),
    "0xd": OpCode("DEC C", 1, 8, "dec", args=["C"], flags={"N": 1}),
    "0xe": OpCode("LD C, d8", 2, 8, "ld", args=["C"]),
    "0xf": OpCode(
        "RRCA",
        1,
        4,
        "rot",
        args=["A", False, True],
        flags={"Z": 0, "N": 0, "H": 0},
    ),
    "0x10": OpCode("STOP", 2, 4, "stop"),
    "0x11": OpCode("LD DE, d16", 3, 12, "ld", args=["DE"]),
    "0x12": OpCode("LD [DE], A", 1, 8, "ld_mem", args=["DE", "A"]),
    "0x13": OpCode("INC DE", 1, 8, "inc", args=["DE"]),
    "0x14": OpCode("INC D", 1, 8, "inc", args=["D"], flags={"N": 0}),
    "0x15": OpCode("DEC D", 1, 8, "dec", args=["D"], flags={"N": 1}),
    "0x16": OpCode("LD D, d8", 2, 8, "ld", args=["D"]),
    "0x17": OpCode(
        "RLA",
        1,
        4,
        "rot",
        args=["A", True, False, True],
        flags={"Z": 0, "N": 0, "H": 0},
    ),
    "0x18": OpCode("JR r8", 2, 12, "jr", pc_inc=False),
    "0x19": OpCode("ADD HL, DE", 1, 8, "add16", args=["HL", "DE"], flags={"N": 0}),
    "0x1a": OpCode("LD A, [DE]", 1, 8, "ld_reg16", args=["A", "DE"]),
    "0x1b": OpCode("DEC DE", 1, 8, "dec", args=["DE"]),
    "0x1c": OpCode("INC E", 1, 8, "inc", args=["E"], flags={"N": 0}),
    "0x1d": OpCode("DEC E", 1, 8, "dec", args=["E"], flags={"N": 1}),
    "0x1e": OpCode("LD E, d8", 2, 8, "ld", args=["E"]),
    "0x1f": OpCode(
        "RRA",
        1,
        4,
        "rot",
        args=["A", False, False, True],
        flags={"Z": 0, "N": 0, "H": 0},
    ),
    "0x20": OpCode("JR NZ, r8", 2, 12, "jrc", args=["Z", 0], pc_inc=False),
    "0x21": OpCode("LD HL, d16", 3, 12, "ld", args=["HL"]),
    "0x22": OpCode("LD [HL+], A", 1, 8, "ld_a_hl_mod", args=[1, True]),
    "0x23": OpCode("INC HL", 1, 8, "inc", args=["HL"]),
    "0x24": OpCode("INC H", 1, 8, "inc", args=["H"], flags={"N": 0}),
    "0x25": OpCode("DEC H", 1, 8, "dec", args=["H"], flags={"N": 1}),
    "0x26": OpCode("LD H, d8", 2, 8, "ld", args=["H"]),
    "0x27": OpCode("DAA", 1, 4, "daa", flags={"H": 0}),
    "0x28": OpCode("JR Z, r8", 2, 12, "jrc", args=["Z", 1], pc_inc=False),
    "0x29": OpCode("ADD HL, HL", 1, 8, "add16", args=["HL", "HL"], flags={"N": 0}),
    "0x2a": OpCode("LD A, [HL+]", 1, 8, "ld_a_hl_mod", args=[1]),
    "0x2b": OpCode("DEC HL", 1, 8, "dec", args=["HL"]),
    "0x2c": OpCode("INC L", 1, 8, "inc", args=["L"], flags={"N": 0}),
    "0x2d": OpCode("DEC L", 1, 8, "dec", args=["L"], flags={"N": 1}),
    "0x2e": OpCode("LD L, d8", 2, 8, "ld", args=["L"]),
    "0x2f": OpCode("CPL", 1, 4, "cpl", args=["A"], flags={"N": 1, "H": 1}),
    "0x30": OpCode("JR NC, r8", 2, 12, "jrc", args=["C", 0], pc_inc=False),
    "0x31": OpCode("LD SP, d16", 3, 12, "ld", args=["SP"]),
    "0x32": OpCode("LD [HL-], A", 1, 8, "ld_a_hl_mod", args=[-1, True]),
    "0x33": OpCode("INC SP", 1, 8, "inc", args=["SP"]),
    "0x34": OpCode("INC [HL]", 1, 12, "inc_mem", args=["HL"], flags={"N": 0}),
    "0x35": OpCode("DEC [HL]", 1, 12, "dec_mem", args=["HL"], flags={"N": 1}),
    "0x36": OpCode("LD [HL], d8", 2, 12, "ld_mem", args=["HL"]),
    "0x37": OpCode("SCF", 1, 4, flags={"N": 0, "H": 0, "C": 1}),
    "0x38": OpCode("JR C, r8", 2, 12, "jrc", args=["C", 1], pc_inc=False),
    "0x39": OpCode("ADD HL, SP", 1, 8, "add16", args=["HL", "SP"], flags={"N": 0}),
    "0x3a": OpCode("LD A, [HL-]", 1, 8, "ld_a_hl_mod", args=[-1]),
    "0x3b": OpCode("DEC SP", 1, 8, "dec", args=["SP"]),
    "0x3c": OpCode("INC A", 1, 8, "inc", args=["A"], flags={"N": 0}),
    "0x3d": OpCode("DEC A", 1, 8, "dec", args=["A"], flags={"N": 1}),
    "0x3e": OpCode("LD A, d8", 2, 8, "ld", args=["A"]),
    "0x3f": OpCode("CCF", 1, 4, "ccf", flags={"N": 0, "H": 0}),
    "0x40": OpCode("LD B, B", 1, 4, "ld", args=["B", "B"]),
    "0x41": OpCode("LD B, C", 1, 4, "ld", args=["B", "C"]),
    "0x42": OpCode("LD B, D", 1, 4, "ld", args=["B", "D"]),
    "0x43": OpCode("LD B, E", 1, 4, "ld", args=["B", "E"]),
    "0x44": OpCode("LD B, H", 1, 4, "ld", args=["B", "H"]),
    "0x45": OpCode("LD B, L", 1, 4, "ld", args=["B", "L"]),
    "0x46": OpCode("LD B, [HL]", 1, 8, "ld_reg16", args=["B", "HL"]),
    "0x47": OpCode("LD B, A", 1, 4, "ld", args=["B", "A"]),
    "0x48": OpCode("LD C, B", 1, 4, "ld", args=["C", "B"]),
    "0x49": OpCode("LD C, C", 1, 4, "ld", args=["C", "C"]),
    "0x4a": OpCode("LD C, D", 1, 4, "ld", args=["C", "D"]),
    "0x4b": OpCode("LD C, E", 1, 4, "ld", args=["C", "E"]),
    "0x4c": OpCode("LD C, H", 1, 4, "ld", args=["C", "H"]),
    "0x4d": OpCode("LD C, L", 1, 4, "ld", args=["C", "L"]),
    "0x4e": OpCode("LD C, [HL]", 1, 8, "ld_reg16", args=["C", "HL"]),
    "0x4f": OpCode("LD C, A", 1, 4, "ld", args=["C", "A"]),
    "0x50": OpCode("LD D, B", 1, 4, "ld", args=["D", "B"]),
    "0x51": OpCode("LD D, C", 1, 4, "ld", args=["D", "C"]),
    "0x52": OpCode("LD D, D", 1, 4, "ld", args=["D", "D"]),
    "0x53": OpCode("LD D, E", 1, 4, "ld", args=["D", "E"]),
    "0x54": OpCode("LD D, H", 1, 4, "ld", args=["D", "H"]),
    "0x55": OpCode("LD D, L", 1, 4, "ld", args=["D", "L"]),
    "0x56": OpCode("LD D, [HL]", 1, 8, "ld_reg16", args=["D", "HL"]),
    "0x57": OpCode("LD D, A", 1, 4, "ld", args=["D", "A"]),
    "0x58": OpCode("LD E, B", 1, 4, "ld", args=["E", "B"]),
    "0x59": OpCode("LD E, C", 1, 4, "ld", args=["E", "C"]),
    "0x5a": OpCode("LD E, D", 1, 4, "ld", args=["E", "D"]),
    "0x5b": OpCode("LD E, E", 1, 4, "ld", args=["E", "E"]),
    "0x5c": OpCode("LD E, H", 1, 4, "ld", args=["E", "H"]),
    "0x5d": OpCode("LD E, L", 1, 4, "ld", args=["E", "L"]),
    "0x5e": OpCode("LD E, [HL]", 1, 8, "ld_reg16", args=["E", "HL"]),
    "0x5f": OpCode("LD E, A", 1, 4, "ld", args=["E", "A"]),
    "0x60": OpCode("LD H, B", 1, 4, "ld", args=["H", "B"]),
    "0x61": OpCode("LD H, C", 1, 4, "ld", args=["H", "C"]),
    "0x62": OpCode("LD H, D", 1, 4, "ld", args=["H", "D"]),
    "0x63": OpCode("LD H, E", 1, 4, "ld", args=["H", "E"]),
    "0x64": OpCode("LD H, H", 1, 4, "ld", args=["H", "H"]),
    "0x65": OpCode("LD H, L", 1, 4, "ld", args=["H", "L"]),
    "0x66": OpCode("LD H, [HL]", 1, 8, "ld_reg16", args=["H", "HL"]),
    "0x67": OpCode("LD H, A", 1, 4, "ld", args=["H", "A"]),
    "0x68": OpCode("LD L, B", 1, 4, "ld", args=["L", "B"]),
    "0x69": OpCode("LD L, C", 1, 4, "ld", args=["L", "C"]),
    "0x6a": OpCode("LD L, D", 1, 4, "ld", args=["L", "D"]),
    "0x6b": OpCode("LD L, E", 1, 4, "ld", args=["L", "E"]),
    "0x6c": OpCode("LD L, H", 1, 4, "ld", args=["L", "H"]),
    "0x6d": OpCode("LD L, L", 1, 4, "ld", args=["L", "L"]),
    "0x6e": OpCode("LD L, [HL]", 1, 8, "ld_reg16", args=["L", "HL"]),
    "0x6f": OpCode("LD L, A", 1, 4, "ld", args=["L", "A"]),
    "0x70": OpCode("LD [HL], B", 1, 8, "ld_mem", args=["HL", "B"]),
    "0x71": OpCode("LD [HL], C", 1, 8, "ld_mem", args=["HL", "C"]),
    "0x72": OpCode("LD [HL], D", 1, 8, "ld_mem", args=["HL", "D"]),
    "0x73": OpCode("LD [HL], E", 1, 8, "ld_mem", args=["HL", "E"]),
    "0x74": OpCode("LD [HL], H", 1, 8, "ld_mem", args=["HL", "H"]),
    "0x75": OpCode("LD [HL], L", 1, 8, "ld_mem", args=["HL", "L"]),
    "0x76": OpCode("HALT", 1, 4, "halt"),  # NEEDS INTERRUPT HANDLING / TESTING
    "0x77": OpCode("LD [HL], A", 1, 8, "ld_mem", args=["HL", "A"]),
    "0x78": OpCode("LD A, B", 1, 4, "ld", args=["A", "B"]),
    "0x79": OpCode("LD A, C", 1, 4, "ld", args=["A", "C"]),
    "0x7a": OpCode("LD A, D", 1, 4, "ld", args=["A", "D"]),
    "0x7b": OpCode("LD A, E", 1, 4, "ld", args=["A", "E"]),
    "0x7c": OpCode("LD A, H", 1, 4, "ld", args=["A", "H"]),
    "0x7d": OpCode("LD A, L", 1, 4, "ld", args=["A", "L"]),
    "0x7e": OpCode("LD A, [HL]", 1, 8, "ld_reg16", args=["A", "HL"]),
    "0x7f": OpCode("LD A, A", 1, 4, "ld", args=["A", "A"]),
    "0x80": OpCode("ADD A, B", 1, 4, "add", args=["A", "B"], flags={"N": 0}),
    "0x81": OpCode("ADD A, C", 1, 4, "add", args=["A", "C"], flags={"N": 0}),
    "0x82": OpCode("ADD A, D", 1, 4, "add", args=["A", "D"], flags={"N": 0}),
    "0x83": OpCode("ADD A, E", 1, 4, "add", args=["A", "E"], flags={"N": 0}),
    "0x84": OpCode("ADD A, H", 1, 4, "add", args=["A", "H"], flags={"N": 0}),
    "0x85": OpCode("ADD A, L", 1, 4, "add", args=["A", "L"], flags={"N": 0}),
    "0x86": OpCode("ADD A, [HL]", 1, 8, "add", args=["A", "HL"], flags={"N": 0}),
    "0x87": OpCode("ADD A, A", 1, 4, "add", args=["A", "A"], flags={"N": 0}),
    "0x88": OpCode("ADC A, B", 1, 4, "add", args=["A", "B", True], flags={"N": 0}),
    "0x89": OpCode("ADC A, C", 1, 4, "add", args=["A", "C", True], flags={"N": 0}),
    "0x8a": OpCode("ADC A, D", 1, 4, "add", args=["A", "D", True], flags={"N": 0}),
    "0x8b": OpCode("ADC A, E", 1, 4, "add", args=["A", "E", True], flags={"N": 0}),
    "0x8c": OpCode("ADC A, H", 1, 4, "add", args=["A", "H", True], flags={"N": 0}),
    "0x8d": OpCode("ADC A, L", 1, 4, "add", args=["A", "L", True], flags={"N": 0}),
    "0x8e": OpCode("ADC A, [HL]", 1, 8, "add", args=["A", "HL", True], flags={"N": 0}),
    "0x8f": OpCode("ADC A, A", 1, 4, "add", args=["A", "A", True], flags={"N": 0}),
    "0x90": OpCode("SUB A, B", 1, 4, "sub", args=["A", "B"], flags={"N": 1}),
    "0x91": OpCode("SUB A, C", 1, 4, "sub", args=["A", "C"], flags={"N": 1}),
    "0x92": OpCode("SUB A, D", 1, 4, "sub", args=["A", "D"], flags={"N": 1}),
    "0x93": OpCode("SUB A, E", 1, 4, "sub", args=["A", "E"], flags={"N": 1}),
    "0x94": OpCode("SUB A, [HL]", 1, 8, "sub", args=["A", "HL"], flags={"N": 1}),
    "0x95": OpCode("SUB A, A", 1, 4, "sub", args=["A", "A"], flags={"N": 1}),
    "0x96": OpCode("SBC A, B", 1, 4, "sub", args=["A", "B", True], flags={"N": 1}),
    "0x97": OpCode("SBC A, C", 1, 4, "sub", args=["A", "C", True], flags={"N": 1}),
    "0x98": OpCode("SBC A, D", 1, 4, "sub", args=["A", "D", True], flags={"N": 1}),
    "0x99": OpCode("SBC A, E", 1, 4, "sub", args=["A", "E", True], flags={"N": 1}),
    "0x9a": OpCode("SBC A, H", 1, 4, "sub", args=["A", "H", True], flags={"N": 1}),
    "0x9b": OpCode("SBC A, L", 1, 4, "sub", args=["A", "L", True], flags={"N": 1}),
    "0x9c": OpCode("SBC A, [HL]", 1, 8, "sub", args=["A", "HL", True], flags={"N": 1}),
    "0x9d": OpCode("SBC A, A", 1, 4, "sub", args=["A", "A", True], flags={"N": 1}),
    "0xa0": OpCode(
        "AND A, B",
        1,
        4,
        "bitwise",
        args=[Bitwise.AND, "A", "B"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa1": OpCode(
        "AND A, C",
        1,
        4,
        "bitwise",
        args=[Bitwise.AND, "A", "C"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa2": OpCode(
        "AND A, D",
        1,
        4,
        "bitwise",
        args=[Bitwise.AND, "A", "D"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa3": OpCode(
        "AND A, E",
        1,
        4,
        "bitwise",
        args=[Bitwise.AND, "A", "E"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa4": OpCode(
        "AND A, H",
        1,
        4,
        "bitwise",
        args=[Bitwise.AND, "A", "H"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa5": OpCode(
        "AND A, L",
        1,
        4,
        "bitwise",
        args=[Bitwise.AND, "A", "L"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa6": OpCode(
        "AND A, [HL]",
        1,
        8,
        "bitwise",
        args=[Bitwise.AND, "A", "HL"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa7": OpCode(
        "AND A, A",
        1,
        4,
        "bitwise",
        args=[Bitwise.AND, "A", "A"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xa8": OpCode(
        "XOR A, B",
        1,
        4,
        "bitwise",
        args=[Bitwise.XOR, "A", "B"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xa9": OpCode(
        "XOR A, C",
        1,
        4,
        "bitwise",
        args=[Bitwise.XOR, "A", "C"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xaa": OpCode(
        "XOR A, D",
        1,
        4,
        "bitwise",
        args=[Bitwise.XOR, "A", "D"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xab": OpCode(
        "XOR A, E",
        1,
        4,
        "bitwise",
        args=[Bitwise.XOR, "A", "E"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xac": OpCode(
        "XOR A, H",
        1,
        4,
        "bitwise",
        args=[Bitwise.XOR, "A", "H"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xad": OpCode(
        "XOR A, L",
        1,
        4,
        "bitwise",
        args=[Bitwise.XOR, "A", "L"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xae": OpCode(
        "XOR A, [HL]",
        1,
        8,
        "bitwise",
        args=[Bitwise.XOR, "A", "HL"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xaf": OpCode(
        "XOR A, A",
        1,
        4,
        "bitwise",
        args=[Bitwise.XOR, "A", "A"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb0": OpCode(
        "OR A, B",
        1,
        4,
        "bitwise",
        args=[Bitwise.OR, "A", "B"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb1": OpCode(
        "OR A, C",
        1,
        4,
        "bitwise",
        args=[Bitwise.OR, "A", "C"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb2": OpCode(
        "OR A, D",
        1,
        4,
        "bitwise",
        args=[Bitwise.OR, "A", "D"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb3": OpCode(
        "OR A, E",
        1,
        4,
        "bitwise",
        args=[Bitwise.OR, "A", "E"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb4": OpCode(
        "OR A, H",
        1,
        4,
        "bitwise",
        args=[Bitwise.OR, "A", "H"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb5": OpCode(
        "OR A, L",
        1,
        4,
        "bitwise",
        args=[Bitwise.OR, "A", "L"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb6": OpCode(
        "OR A, [HL]",
        1,
        8,
        "bitwise",
        args=[Bitwise.OR, "A", "HL"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb7": OpCode(
        "OR A, A",
        1,
        4,
        "bitwise",
        args=[Bitwise.OR, "A", "A"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xb8": OpCode(
        "CP A, B",
        1,
        4,
        "cp",
        args=["A", "B"],
        flags={"N": 1},
    ),
    "0xb9": OpCode(
        "CP A, C",
        1,
        4,
        "cp",
        args=["A", "C"],
        flags={"N": 1},
    ),
    "0xba": OpCode(
        "CP A, D",
        1,
        4,
        "cp",
        args=["A", "D"],
        flags={"N": 1},
    ),
    "0xbb": OpCode(
        "CP A, E",
        1,
        4,
        "cp",
        args=["A", "E"],
        flags={"N": 1},
    ),
    "0xbc": OpCode(
        "CP A, H",
        1,
        4,
        "cp",
        args=["A", "H"],
        flags={"N": 1},
    ),
    "0xbd": OpCode(
        "CP A, L",
        1,
        4,
        "cp",
        args=["A", "L"],
        flags={"N": 1},
    ),
    "0xbe": OpCode(
        "CP A, [HL]",
        1,
        8,
        "cp",
        args=["A", "HL"],
        flags={"N": 1},
    ),
    "0xbf": OpCode(
        "CP A, A",
        1,
        4,
        "cp",
        args=["A", "A"],
        flags={"N": 1, "Z": 1, "H": 0, "C": 0},
    ),
    "0xc0": OpCode("RET NZ", 1, 20, "ret", args=["Z", 0], pc_inc=False),
    "0xc1": OpCode("POP BC", 1, 12, "pop", args=["BC"]),
    "0xc2": OpCode("JP NZ, a16", 3, 16, "jpc", args=["Z", 0], pc_inc=False),
    "0xc3": OpCode("JP a16", 3, 16, "jp", pc_inc=False),
    "0xc4": OpCode("CALL NZ, a16", 3, 24, "callc", args=["Z", 0], pc_inc=False),
    "0xc5": OpCode("PUSH BC", 1, 16, "push", args=["BC"]),
    "0xc6": OpCode("ADD A, d8", 2, 8, "add", args=["A", False], flags={"N": 0}),
    "0xc7": OpCode("RST $00", 1, 16, "rst", args=[0x00], pc_inc=False),
    "0xca": OpCode("JP Z, a16", 3, 16, "jpc", args=["Z", 1], pc_inc=False),
    "0xcc": OpCode("CALL Z, a16", 3, 24, "callc", args=["Z", 1], pc_inc=False),
    "0xcd": OpCode("CALL a16", 3, 24, "call", pc_inc=False),
    "0xce": OpCode("ADC A, d8", 2, 8, "add", args=["A", True], flags={"N": 0}),
    "0xcf": OpCode("RST $08", 1, 16, "rst", args=[0x08], pc_inc=False),
    "0xd1": OpCode("POP DE", 1, 12, "pop", args=["DE"]),
    "0xd2": OpCode("JP NC, a16", 3, 16, "jpc", args=["C", 0], pc_inc=False),
    "0xd4": OpCode("CALL NC, a16", 3, 24, "callc", args=["C", 0], pc_inc=False),
    "0xd5": OpCode("PUSH DE", 1, 16, "push", args=["DE"]),
    "0xd6": OpCode("SUB A, d8", 2, 8, "sub", args=["A", False], flags={"N": 1}),
    "0xd7": OpCode("RST $10", 1, 16, "rst", args=[0x10], pc_inc=False),
    "0xda": OpCode("JP C, a16", 3, 16, "jpc", args=["C", 1], pc_inc=False),
    "0xdc": OpCode("CALL C, a16", 3, 24, "callc", args=["C", 1], pc_inc=False),
    "0xde": OpCode("SBC A, d8", 2, 8, "sub", args=["A", True], flags={"N": 1}),
    "0xdf": OpCode("RST $18", 1, 16, "rst", args=[0x18], pc_inc=False),
    "0xe0": OpCode("LDH [a8], A", 2, 12, "ldh_mem", args=["A"]),
    "0xe1": OpCode("POP HL", 1, 12, "pop", args=["HL"]),
    "0xe2": OpCode("LDH [C], A", 1, 8, "ldh_mem", args=["A", "C"]),
    "0xe5": OpCode("PUSH HL", 1, 16, "push", args=["HL"]),
    "0xe6": OpCode(
        "AND A, d8",
        2,
        8,
        "bitwise",
        args=[Bitwise.AND, "A"],
        flags={"N": 0, "H": 1, "C": 0},
    ),
    "0xe7": OpCode("RST $20", 1, 16, "rst", args=[0x20], pc_inc=False),
    "0xe9": OpCode("JP HL", 1, 4, "jp", args=["HL"], pc_inc=False),
    "0xea": OpCode("LD [a16], A", 3, 16, "ld_mem16", args=["A"]),
    "0xee": OpCode(
        "XOR A, d8",
        2,
        8,
        "bitwise",
        args=[Bitwise.XOR, "A"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xef": OpCode("RST $28", 1, 16, "rst", args=[0x28], pc_inc=False),
    "0xf0": OpCode("LDH A, [a8]", 2, 12, "ldh_reg", args=["A"]),
    "0xf1": OpCode("POP AF", 1, 12, "pop", args=["AF"]),
    "0xf2": OpCode("LDH A, [C]", 1, 8, "ldh_reg", args=["A", "C"]),
    "0xf3": OpCode("DI", 1, 4, "di"),
    "0xf5": OpCode("PUSH AF", 1, 16, "push", args=["AF"]),
    "0xf6": OpCode(
        "OR A, d8",
        2,
        8,
        "bitwise",
        args=[Bitwise.OR, "A"],
        flags={"N": 0, "H": 0, "C": 0},
    ),
    "0xf7": OpCode("RST $30", 1, 16, "rst", args=[0x30], pc_inc=False),
    "0xfa": OpCode("LD A, [a16]", 3, 16, "ld_reg16", args=["A"]),
    "0xfb": OpCode("EI", 1, 4, "ei"),
    "0xfe": OpCode(
        "CP A, d8",
        2,
        8,
        "cp",
        args=["A"],
        flags={"N": 1},
    ),
    "0xff": OpCode("RST $38", 1, 16, "rst", args=[0x38], pc_inc=False),
}


CB_PREFIXED: dict[str, OpCode] = {
    "0x0": OpCode("RLC B", 2, 8, "rot", args=["B", True, True], flags={"N": 0, "H": 0}),
    "0x1": OpCode("RLC C", 2, 8, "rot", args=["C", True, True], flags={"N": 0, "H": 0}),
    "0x2": OpCode("RLC D", 2, 8, "rot", args=["D", True, True], flags={"N": 0, "H": 0}),
    "0x3": OpCode("RLC E", 2, 8, "rot", args=["E", True, True], flags={"N": 0, "H": 0}),
    "0x4": OpCode("RLC H", 2, 8, "rot", args=["H", True, True], flags={"N": 0, "H": 0}),
    "0x5": OpCode("RLC L", 2, 8, "rot", args=["L", True, True], flags={"N": 0, "H": 0}),
    "0x6": OpCode("RLC [HL]", 2, 16, "rot", args=["HL", True, True], flags={"N": 0, "H": 0}),
    "0x7": OpCode("RLC A", 2, 8, "rot", args=["A", True, True], flags={"N": 0, "H": 0}),
    "0x8": OpCode("RRC B", 2, 8, "rot", args=["B", False, True], flags={"N": 0, "H": 0}),
    "0x9": OpCode("RRC C", 2, 8, "rot", args=["C", False, True], flags={"N": 0, "H": 0}),
    "0xa": OpCode("RRC D", 2, 8, "rot", args=["D", False, True], flags={"N": 0, "H": 0}),
    "0xb": OpCode("RRC E", 2, 8, "rot", args=["E", False, True], flags={"N": 0, "H": 0}),
    "0xc": OpCode("RRC H", 2, 8, "rot", args=["H", False, True], flags={"N": 0, "H": 0}),
    "0xd": OpCode("RRC L", 2, 8, "rot", args=["L", False, True], flags={"N": 0, "H": 0}),
    "0xe": OpCode("RRC [HL]", 2, 16, "rot", args=["HL", False, True], flags={"N": 0, "H": 0}),
    "0xf": OpCode("RRC A", 2, 8, "rot", args=["A", False, True], flags={"N": 0, "H": 0}),
    "0x10": OpCode("RL B", 2, 8, "rot", args=["B", True, True, True], flags={"N": 0, "H": 0}),
    "0x11": OpCode("RL C", 2, 8, "rot", args=["C", True, True, True], flags={"N": 0, "H": 0}),
    "0x12": OpCode("RL D", 2, 8, "rot", args=["D", True, True, True], flags={"N": 0, "H": 0}),
    "0x13": OpCode("RL E", 2, 8, "rot", args=["E", True, True, True], flags={"N": 0, "H": 0}),
    "0x14": OpCode("RL H", 2, 8, "rot", args=["H", True, True, True], flags={"N": 0, "H": 0}),
    "0x15": OpCode("RL L", 2, 8, "rot", args=["L", True, True, True], flags={"N": 0, "H": 0}),
    "0x16": OpCode("RL [HL]", 2, 16, "rot", args=["HL", True, True, True], flags={"N": 0, "H": 0}),
    "0x17": OpCode("RL A", 2, 8, "rot", args=["A", True, True, True], flags={"N": 0, "H": 0}),
    "0x18": OpCode("RR B", 2, 8, "rot", args=["B", False, True, True], flags={"N": 0, "H": 0}),
    "0x19": OpCode("RR C", 2, 8, "rot", args=["C", False, True, True], flags={"N": 0, "H": 0}),
    "0x1a": OpCode("RR D", 2, 8, "rot", args=["D", False, True, True], flags={"N": 0, "H": 0}),
    "0x1b": OpCode("RR E", 2, 8, "rot", args=["E", False, True, True], flags={"N": 0, "H": 0}),
    "0x1c": OpCode("RR H", 2, 8, "rot", args=["H", False, True, True], flags={"N": 0, "H": 0}),
    "0x1d": OpCode("RR L", 2, 8, "rot", args=["L", False, True, True], flags={"N": 0, "H": 0}),
    "0x1e": OpCode("RR [HL]", 2, 16, "rot", args=["HL", False, True, True], flags={"N": 0, "H": 0}),
    "0x1f": OpCode("RR A", 2, 8, "rot", args=["A", False, True, True], flags={"N": 0, "H": 0}),
    "0x20": OpCode("SLA B", 2, 8, "shift", args=["B", True, True], flags={"N": 0, "H": 0}),
    "0x21": OpCode("SLA C", 2, 8, "shift", args=["C", True, True], flags={"N": 0, "H": 0}),
    "0x22": OpCode("SLA D", 2, 8, "shift", args=["D", True, True], flags={"N": 0, "H": 0}),
    "0x23": OpCode("SLA E", 2, 8, "shift", args=["E", True, True], flags={"N": 0, "H": 0}),
    "0x24": OpCode("SLA H", 2, 8, "shift", args=["H", True, True], flags={"N": 0, "H": 0}),
    "0x25": OpCode("SLA L", 2, 8, "shift", args=["L", True, True], flags={"N": 0, "H": 0}),
    "0x26": OpCode("SLA [HL]", 2, 16, "shift", args=["HL", True, True], flags={"N": 0, "H": 0}),
    "0x27": OpCode("SLA A", 2, 8, "shift", args=["A", True, True], flags={"N": 0, "H": 0}),
    "0x28": OpCode(
        "SRA B",
        2,
        8,
        "shift",
        args=["B", False, True],
        flags={"N": 0, "H": 0},
    ),
    "0x29": OpCode(
        "SRA C",
        2,
        8,
        "shift",
        args=["C", False, True],
        flags={"N": 0, "H": 0},
    ),
    "0x2a": OpCode(
        "SRA D",
        2,
        8,
        "shift",
        args=["D", False, True],
        flags={"N": 0, "H": 0},
    ),
    "0x2b": OpCode(
        "SRA E",
        2,
        8,
        "shift",
        args=["E", False, True],
        flags={"N": 0, "H": 0},
    ),
    "0x2c": OpCode(
        "SRA H",
        2,
        8,
        "shift",
        args=["H", False, True],
        flags={"N": 0, "H": 0},
    ),
    "0x2d": OpCode(
        "SRA L",
        2,
        8,
        "shift",
        args=["L", False, True],
        flags={"N": 0, "H": 0},
    ),
    "0x2e": OpCode(
        "SRA [HL]",
        2,
        16,
        "shift",
        args=["HL", False, True],
        flags={"N": 0, "H": 0},
    ),
    "0x2f": OpCode(
        "SRA A",
        2,
        8,
        "shift",
        args=["A", False, True],
        flags={"N": 0, "H": 0},
    ),
    "0x30": OpCode("SWAP B", 2, 8, "swap", args=["B"], flags={"N": 0, "H": 0, "C": 0}),
    "0x31": OpCode("SWAP C", 2, 8, "swap", args=["C"], flags={"N": 0, "H": 0, "C": 0}),
    "0x32": OpCode("SWAP D", 2, 8, "swap", args=["D"], flags={"N": 0, "H": 0, "C": 0}),
    "0x33": OpCode("SWAP E", 2, 8, "swap", args=["E"], flags={"N": 0, "H": 0, "C": 0}),
    "0x34": OpCode("SWAP H", 2, 8, "swap", args=["H"], flags={"N": 0, "H": 0, "C": 0}),
    "0x35": OpCode("SWAP L", 2, 8, "swap", args=["L"], flags={"N": 0, "H": 0, "C": 0}),
    "0x36": OpCode("SWAP [HL]", 2, 16, "swap", args=["HL"], flags={"N": 0, "H": 0, "C": 0}),
    "0x37": OpCode("SWAP A", 2, 8, "swap", args=["A"], flags={"N": 0, "H": 0, "C": 0}),
    "0x38": OpCode("SRL B", 2, 8, "shift", args=["B"], flags={"N": 0, "H": 0}),
    "0x39": OpCode("SRL C", 2, 8, "shift", args=["C"], flags={"N": 0, "H": 0}),
    "0x3a": OpCode("SRL D", 2, 8, "shift", args=["D"], flags={"N": 0, "H": 0}),
    "0x3b": OpCode("SRL E", 2, 8, "shift", args=["E"], flags={"N": 0, "H": 0}),
    "0x3c": OpCode("SRL H", 2, 8, "shift", args=["H"], flags={"N": 0, "H": 0}),
    "0x3d": OpCode("SRL L", 2, 8, "shift", args=["L"], flags={"N": 0, "H": 0}),
    "0x3e": OpCode("SRL [HL]", 2, 16, "shift", args=["HL"], flags={"N": 0, "H": 0}),
    "0x3f": OpCode("SRL A", 2, 8, "shift", args=["A"], flags={"N": 0, "H": 0}),
    "0x40": OpCode("BIT 0, B", 2, 8, "bit", args=[0, "B"], flags={"N": 0, "H": 1}),
    "0x41": OpCode("BIT 0, C", 2, 8, "bit", args=[0, "C"], flags={"N": 0, "H": 1}),
    "0x42": OpCode("BIT 0, D", 2, 8, "bit", args=[0, "D"], flags={"N": 0, "H": 1}),
    "0x43": OpCode("BIT 0, E", 2, 8, "bit", args=[0, "E"], flags={"N": 0, "H": 1}),
    "0x44": OpCode("BIT 0, H", 2, 8, "bit", args=[0, "H"], flags={"N": 0, "H": 1}),
    "0x45": OpCode("BIT 0, L", 2, 8, "bit", args=[0, "L"], flags={"N": 0, "H": 1}),
    "0x46": OpCode("BIT 0, [HL]", 2, 16, "bit", args=[0, "HL"], flags={"N": 0, "H": 1}),
    "0x47": OpCode("BIT 0, A", 2, 8, "bit", args=[0, "A"], flags={"N": 0, "H": 1}),
    "0x48": OpCode("BIT 1, B", 2, 8, "bit", args=[1, "B"], flags={"N": 0, "H": 1}),
    "0x49": OpCode("BIT 1, C", 2, 8, "bit", args=[1, "C"], flags={"N": 0, "H": 1}),
    "0x4a": OpCode("BIT 1, D", 2, 8, "bit", args=[1, "D"], flags={"N": 0, "H": 1}),
    "0x4b": OpCode("BIT 1, E", 2, 8, "bit", args=[1, "E"], flags={"N": 0, "H": 1}),
    "0x4c": OpCode("BIT 1, H", 2, 8, "bit", args=[1, "H"], flags={"N": 0, "H": 1}),
    "0x4d": OpCode("BIT 1, L", 2, 8, "bit", args=[1, "L"], flags={"N": 0, "H": 1}),
    "0x4e": OpCode("BIT 1, [HL]", 2, 16, "bit", args=[1, "HL"], flags={"N": 0, "H": 1}),
    "0x4f": OpCode("BIT 1, A", 2, 8, "bit", args=[1, "A"], flags={"N": 0, "H": 1}),
    "0x50": OpCode("BIT 2, B", 2, 8, "bit", args=[2, "B"], flags={"N": 0, "H": 1}),
    "0x51": OpCode("BIT 2, C", 2, 8, "bit", args=[2, "C"], flags={"N": 0, "H": 1}),
    "0x52": OpCode("BIT 2, D", 2, 8, "bit", args=[2, "D"], flags={"N": 0, "H": 1}),
    "0x53": OpCode("BIT 2, E", 2, 8, "bit", args=[2, "E"], flags={"N": 0, "H": 1}),
    "0x54": OpCode("BIT 2, H", 2, 8, "bit", args=[2, "H"], flags={"N": 0, "H": 1}),
    "0x55": OpCode("BIT 2, L", 2, 8, "bit", args=[2, "L"], flags={"N": 0, "H": 1}),
    "0x56": OpCode("BIT 2, [HL]", 2, 16, "bit", args=[2, "HL"], flags={"N": 0, "H": 1}),
    "0x57": OpCode("BIT 2, A", 2, 8, "bit", args=[2, "A"], flags={"N": 0, "H": 1}),
    "0x58": OpCode("BIT 3, B", 2, 8, "bit", args=[3, "B"], flags={"N": 0, "H": 1}),
    "0x59": OpCode("BIT 3, C", 2, 8, "bit", args=[3, "C"], flags={"N": 0, "H": 1}),
    "0x5a": OpCode("BIT 3, D", 2, 8, "bit", args=[3, "D"], flags={"N": 0, "H": 1}),
    "0x5b": OpCode("BIT 3, E", 2, 8, "bit", args=[3, "E"], flags={"N": 0, "H": 1}),
    "0x5c": OpCode("BIT 3, H", 2, 8, "bit", args=[3, "H"], flags={"N": 0, "H": 1}),
    "0x5d": OpCode("BIT 3, L", 2, 8, "bit", args=[3, "L"], flags={"N": 0, "H": 1}),
    "0x5e": OpCode("BIT 3, [HL]", 2, 16, "bit", args=[3, "HL"], flags={"N": 0, "H": 1}),
    "0x5f": OpCode("BIT 3, A", 2, 8, "bit", args=[3, "A"], flags={"N": 0, "H": 1}),
    "0x60": OpCode("BIT 4, B", 2, 8, "bit", args=[4, "B"], flags={"N": 0, "H": 1}),
    "0x61": OpCode("BIT 4, C", 2, 8, "bit", args=[4, "C"], flags={"N": 0, "H": 1}),
    "0x62": OpCode("BIT 4, D", 2, 8, "bit", args=[4, "D"], flags={"N": 0, "H": 1}),
    "0x63": OpCode("BIT 4, E", 2, 8, "bit", args=[4, "E"], flags={"N": 0, "H": 1}),
    "0x64": OpCode("BIT 4, H", 2, 8, "bit", args=[4, "H"], flags={"N": 0, "H": 1}),
    "0x65": OpCode("BIT 4, L", 2, 8, "bit", args=[4, "L"], flags={"N": 0, "H": 1}),
    "0x66": OpCode("BIT 4, [HL]", 2, 16, "bit", args=[4, "HL"], flags={"N": 0, "H": 1}),
    "0x67": OpCode("BIT 4, A", 2, 8, "bit", args=[4, "A"], flags={"N": 0, "H": 1}),
    "0x68": OpCode("BIT 5, B", 2, 8, "bit", args=[5, "B"], flags={"N": 0, "H": 1}),
    "0x69": OpCode("BIT 5, C", 2, 8, "bit", args=[5, "C"], flags={"N": 0, "H": 1}),
    "0x6a": OpCode("BIT 5, D", 2, 8, "bit", args=[5, "D"], flags={"N": 0, "H": 1}),
    "0x6b": OpCode("BIT 5, E", 2, 8, "bit", args=[5, "E"], flags={"N": 0, "H": 1}),
    "0x6c": OpCode("BIT 5, H", 2, 8, "bit", args=[5, "H"], flags={"N": 0, "H": 1}),
    "0x6d": OpCode("BIT 5, L", 2, 8, "bit", args=[5, "L"], flags={"N": 0, "H": 1}),
    "0x6e": OpCode("BIT 5, [HL]", 2, 16, "bit", args=[5, "HL"], flags={"N": 0, "H": 1}),
    "0x6f": OpCode("BIT 5, A", 2, 8, "bit", args=[5, "A"], flags={"N": 0, "H": 1}),
    "0x70": OpCode("BIT 6, B", 2, 8, "bit", args=[6, "B"], flags={"N": 0, "H": 1}),
    "0x71": OpCode("BIT 6, C", 2, 8, "bit", args=[6, "C"], flags={"N": 0, "H": 1}),
    "0x72": OpCode("BIT 6, D", 2, 8, "bit", args=[6, "D"], flags={"N": 0, "H": 1}),
    "0x73": OpCode("BIT 6, E", 2, 8, "bit", args=[6, "E"], flags={"N": 0, "H": 1}),
    "0x74": OpCode("BIT 6, H", 2, 8, "bit", args=[6, "H"], flags={"N": 0, "H": 1}),
    "0x75": OpCode("BIT 6, L", 2, 8, "bit", args=[6, "L"], flags={"N": 0, "H": 1}),
    "0x76": OpCode("BIT 6, [HL]", 2, 16, "bit", args=[6, "HL"], flags={"N": 0, "H": 1}),
    "0x77": OpCode("BIT 6, A", 2, 8, "bit", args=[6, "A"], flags={"N": 0, "H": 1}),
    "0x78": OpCode("BIT 7, B", 2, 8, "bit", args=[7, "B"], flags={"N": 0, "H": 1}),
    "0x79": OpCode("BIT 7, C", 2, 8, "bit", args=[7, "C"], flags={"N": 0, "H": 1}),
    "0x7a": OpCode("BIT 7, D", 2, 8, "bit", args=[7, "D"], flags={"N": 0, "H": 1}),
    "0x7b": OpCode("BIT 7, E", 2, 8, "bit", args=[7, "E"], flags={"N": 0, "H": 1}),
    "0x7c": OpCode("BIT 7, H", 2, 8, "bit", args=[7, "H"], flags={"N": 0, "H": 1}),
    "0x7d": OpCode("BIT 7, L", 2, 8, "bit", args=[7, "L"], flags={"N": 0, "H": 1}),
    "0x7e": OpCode("BIT 7, [HL]", 2, 16, "bit", args=[7, "HL"], flags={"N": 0, "H": 1}),
    "0x7f": OpCode("BIT 7, A", 2, 8, "bit", args=[7, "A"], flags={"N": 0, "H": 1}),
    "0x80": OpCode("RES 0, B", 2, 8, "res", args=[0, "B"]),
    "0x81": OpCode("RES 0, C", 2, 8, "res", args=[0, "C"]),
    "0x82": OpCode("RES 0, D", 2, 8, "res", args=[0, "D"]),
    "0x83": OpCode("RES 0, E", 2, 8, "res", args=[0, "E"]),
    "0x84": OpCode("RES 0, H", 2, 8, "res", args=[0, "H"]),
    "0x85": OpCode("RES 0, L", 2, 8, "res", args=[0, "L"]),
    "0x86": OpCode("RES 0, [HL]", 2, 16, "res", args=[0, "HL"]),
    "0x87": OpCode("RES 0, A", 2, 8, "res", args=[0, "A"]),
    "0x88": OpCode("RES 1, B", 2, 8, "res", args=[1, "B"]),
    "0x89": OpCode("RES 1, C", 2, 8, "res", args=[1, "C"]),
    "0x8a": OpCode("RES 1, D", 2, 8, "res", args=[1, "D"]),
    "0x8b": OpCode("RES 1, E", 2, 8, "res", args=[1, "E"]),
    "0x8c": OpCode("RES 1, H", 2, 8, "res", args=[1, "H"]),
    "0x8d": OpCode("RES 1, L", 2, 8, "res", args=[1, "L"]),
    "0x8e": OpCode("RES 1, [HL]", 2, 16, "res", args=[1, "HL"]),
    "0x8f": OpCode("RES 1, A", 2, 8, "res", args=[1, "A"]),
    "0x90": OpCode("RES 2, B", 2, 8, "res", args=[2, "B"]),
    "0x91": OpCode("RES 2, C", 2, 8, "res", args=[2, "C"]),
    "0x92": OpCode("RES 2, D", 2, 8, "res", args=[2, "D"]),
    "0x93": OpCode("RES 2, E", 2, 8, "res", args=[2, "E"]),
    "0x94": OpCode("RES 2, H", 2, 8, "res", args=[2, "H"]),
    "0x95": OpCode("RES 2, L", 2, 8, "res", args=[2, "L"]),
    "0x96": OpCode("RES 2, [HL]", 2, 16, "res", args=[2, "HL"]),
    "0x97": OpCode("RES 2, A", 2, 8, "res", args=[2, "A"]),
    "0x98": OpCode("RES 3, B", 2, 8, "res", args=[3, "B"]),
    "0x99": OpCode("RES 3, C", 2, 8, "res", args=[3, "C"]),
    "0x9a": OpCode("RES 3, D", 2, 8, "res", args=[3, "D"]),
    "0x9b": OpCode("RES 3, E", 2, 8, "res", args=[3, "E"]),
    "0x9c": OpCode("RES 3, H", 2, 8, "res", args=[3, "H"]),
    "0x9d": OpCode("RES 3, L", 2, 8, "res", args=[3, "L"]),
    "0x9e": OpCode("RES 3, [HL]", 2, 16, "res", args=[3, "HL"]),
    "0x9f": OpCode("RES 3, A", 2, 8, "res", args=[3, "A"]),
    "0xa0": OpCode("RES 4, B", 2, 8, "res", args=[4, "B"]),
    "0xa1": OpCode("RES 4, C", 2, 8, "res", args=[4, "C"]),
    "0xa2": OpCode("RES 4, D", 2, 8, "res", args=[4, "D"]),
    "0xa3": OpCode("RES 4, E", 2, 8, "res", args=[4, "E"]),
    "0xa4": OpCode("RES 4, H", 2, 8, "res", args=[4, "H"]),
    "0xa5": OpCode("RES 4, L", 2, 8, "res", args=[4, "L"]),
    "0xa6": OpCode("RES 4, [HL]", 2, 16, "res", args=[4, "HL"]),
    "0xa7": OpCode("RES 4, A", 2, 8, "res", args=[4, "A"]),
    "0xa8": OpCode("RES 5, B", 2, 8, "res", args=[5, "B"]),
    "0xa9": OpCode("RES 5, C", 2, 8, "res", args=[5, "C"]),
    "0xaa": OpCode("RES 5, D", 2, 8, "res", args=[5, "D"]),
    "0xab": OpCode("RES 5, E", 2, 8, "res", args=[5, "E"]),
    "0xac": OpCode("RES 5, H", 2, 8, "res", args=[5, "H"]),
    "0xad": OpCode("RES 5, L", 2, 8, "res", args=[5, "L"]),
    "0xae": OpCode("RES 5, [HL]", 2, 16, "res", args=[5, "HL"]),
    "0xaf": OpCode("RES 5, A", 2, 8, "res", args=[5, "A"]),
    "0xb0": OpCode("RES 6, B", 2, 8, "res", args=[6, "B"]),
    "0xb1": OpCode("RES 6, C", 2, 8, "res", args=[6, "C"]),
    "0xb2": OpCode("RES 6, D", 2, 8, "res", args=[6, "D"]),
    "0xb3": OpCode("RES 6, E", 2, 8, "res", args=[6, "E"]),
    "0xb4": OpCode("RES 6, H", 2, 8, "res", args=[6, "H"]),
    "0xb5": OpCode("RES 6, L", 2, 8, "res", args=[6, "L"]),
    "0xb6": OpCode("RES 6, [HL]", 2, 16, "res", args=[6, "HL"]),
    "0xb7": OpCode("RES 6, A", 2, 8, "res", args=[6, "A"]),
    "0xb8": OpCode("RES 7, B", 2, 8, "res", args=[7, "B"]),
    "0xb9": OpCode("RES 7, C", 2, 8, "res", args=[7, "C"]),
    "0xba": OpCode("RES 7, D", 2, 8, "res", args=[7, "D"]),
    "0xbb": OpCode("RES 7, E", 2, 8, "res", args=[7, "E"]),
    "0xbc": OpCode("RES 7, H", 2, 8, "res", args=[7, "H"]),
    "0xbd": OpCode("RES 7, L", 2, 8, "res", args=[7, "L"]),
    "0xbe": OpCode("RES 7, [HL]", 2, 16, "res", args=[7, "HL"]),
    "0xbf": OpCode("RES 7, A", 2, 8, "res", args=[7, "A"]),
    "0xc0": OpCode("SET 0, B", 2, 8, "set", args=[0, "B"]),
    "0xc1": OpCode("SET 0, C", 2, 8, "set", args=[0, "C"]),
    "0xc2": OpCode("SET 0, D", 2, 8, "set", args=[0, "D"]),
    "0xc3": OpCode("SET 0, E", 2, 8, "set", args=[0, "E"]),
    "0xc4": OpCode("SET 0, H", 2, 8, "set", args=[0, "H"]),
    "0xc5": OpCode("SET 0, L", 2, 8, "set", args=[0, "L"]),
    "0xc6": OpCode("SET 0, [HL]", 2, 16, "set", args=[0, "HL"]),
    "0xc7": OpCode("SET 0, A", 2, 8, "set", args=[0, "A"]),
    "0xc8": OpCode("SET 1, B", 2, 8, "set", args=[1, "B"]),
    "0xc9": OpCode("SET 1, C", 2, 8, "set", args=[1, "C"]),
    "0xca": OpCode("SET 1, D", 2, 8, "set", args=[1, "D"]),
    "0xcb": OpCode("SET 1, E", 2, 8, "set", args=[1, "E"]),
    "0xcc": OpCode("SET 1, H", 2, 8, "set", args=[1, "H"]),
    "0xcd": OpCode("SET 1, L", 2, 8, "set", args=[1, "L"]),
    "0xce": OpCode("SET 1, [HL]", 2, 16, "set", args=[1, "HL"]),
    "0xcf": OpCode("SET 1, A", 2, 8, "set", args=[1, "A"]),
    "0xd0": OpCode("SET 2, B", 2, 8, "set", args=[2, "B"]),
    "0xd1": OpCode("SET 2, C", 2, 8, "set", args=[2, "C"]),
    "0xd2": OpCode("SET 2, D", 2, 8, "set", args=[2, "D"]),
    "0xd3": OpCode("SET 2, E", 2, 8, "set", args=[2, "E"]),
    "0xd4": OpCode("SET 2, H", 2, 8, "set", args=[2, "H"]),
    "0xd5": OpCode("SET 2, L", 2, 8, "set", args=[2, "L"]),
    "0xd6": OpCode("SET 2, [HL]", 2, 16, "set", args=[2, "HL"]),
    "0xd7": OpCode("SET 2, A", 2, 8, "set", args=[2, "A"]),
    "0xd8": OpCode("SET 3, B", 2, 8, "set", args=[3, "B"]),
    "0xd9": OpCode("SET 3, C", 2, 8, "set", args=[3, "C"]),
    "0xda": OpCode("SET 3, D", 2, 8, "set", args=[3, "D"]),
    "0xdb": OpCode("SET 3, E", 2, 8, "set", args=[3, "E"]),
    "0xdc": OpCode("SET 3, H", 2, 8, "set", args=[3, "H"]),
    "0xdd": OpCode("SET 3, L", 2, 8, "set", args=[3, "L"]),
    "0xde": OpCode("SET 3, [HL]", 2, 16, "set", args=[3, "HL"]),
    "0xdf": OpCode("SET 3, A", 2, 8, "set", args=[3, "A"]),
    "0xe0": OpCode("SET 4, B", 2, 8, "set", args=[4, "B"]),
    "0xe1": OpCode("SET 4, C", 2, 8, "set", args=[4, "C"]),
    "0xe2": OpCode("SET 4, D", 2, 8, "set", args=[4, "D"]),
    "0xe3": OpCode("SET 4, E", 2, 8, "set", args=[4, "E"]),
    "0xe4": OpCode("SET 4, H", 2, 8, "set", args=[4, "H"]),
    "0xe5": OpCode("SET 4, L", 2, 8, "set", args=[4, "L"]),
    "0xe6": OpCode("SET 4, [HL]", 2, 16, "set", args=[4, "HL"]),
    "0xe7": OpCode("SET 4, A", 2, 8, "set", args=[4, "A"]),
    "0xe8": OpCode("SET 5, B", 2, 8, "set", args=[5, "B"]),
    "0xe9": OpCode("SET 5, C", 2, 8, "set", args=[5, "C"]),
    "0xea": OpCode("SET 5, D", 2, 8, "set", args=[5, "D"]),
    "0xeb": OpCode("SET 5, E", 2, 8, "set", args=[5, "E"]),
    "0xec": OpCode("SET 5, H", 2, 8, "set", args=[5, "H"]),
    "0xed": OpCode("SET 5, L", 2, 8, "set", args=[5, "L"]),
    "0xee": OpCode("SET 5, [HL]", 2, 16, "set", args=[5, "HL"]),
    "0xef": OpCode("SET 5, A", 2, 8, "set", args=[5, "A"]),
    "0xf0": OpCode("SET 6, B", 2, 8, "set", args=[6, "B"]),
    "0xf1": OpCode("SET 6, C", 2, 8, "set", args=[6, "C"]),
    "0xf2": OpCode("SET 6, D", 2, 8, "set", args=[6, "D"]),
    "0xf3": OpCode("SET 6, E", 2, 8, "set", args=[6, "E"]),
    "0xf4": OpCode("SET 6, H", 2, 8, "set", args=[6, "H"]),
    "0xf5": OpCode("SET 6, L", 2, 8, "set", args=[6, "L"]),
    "0xf6": OpCode("SET 6, [HL]", 2, 16, "set", args=[6, "HL"]),
    "0xf7": OpCode("SET 6, A", 2, 8, "set", args=[6, "A"]),
    "0xf8": OpCode("SET 7, B", 2, 8, "set", args=[7, "B"]),
    "0xf9": OpCode("SET 7, C", 2, 8, "set", args=[7, "C"]),
    "0xfa": OpCode("SET 7, D", 2, 8, "set", args=[7, "D"]),
    "0xfb": OpCode("SET 7, E", 2, 8, "set", args=[7, "E"]),
    "0xfc": OpCode("SET 7, H", 2, 8, "set", args=[7, "H"]),
    "0xfd": OpCode("SET 7, L", 2, 8, "set", args=[7, "L"]),
    "0xfe": OpCode("SET 7, [HL]", 2, 16, "set", args=[7, "HL"]),
    "0xff": OpCode("SET 7, A", 2, 8, "set", args=[7, "A"]),
}
